import type { Metadata } from 'next';

import { StoreProvider } from '@/components/providers/StoreProvider';

import '@/styles/globals.css';

export const metadata: Metadata = {
  title: 'Jornada do Herói',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <StoreProvider>
        <body>{children}</body>
      </StoreProvider>
    </html>
  );
}
