import type { Metadata } from 'next';
import { Bangers } from 'next/font/google';

import { StoreProvider } from '@/components/providers/StoreProvider';
import ThemeProvider from '@/components/providers/theme-provider/ThemeProvider';

import '@/styles/globals.css';

const bangers = Bangers({
  weight: ['400'],
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Jornada do Herói',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <StoreProvider>
        <ThemeProvider>
          <body className={bangers.className}>{children}</body>
        </ThemeProvider>
      </StoreProvider>
    </html>
  );
}
